theme: minima
title: Memory Agent
description: >-
  A Python library for advanced memory management in AI agent applications
version: 1.0.42
minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/giuseppezileni/memory_agent" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/gzileni" }