theme: minima
title: Memory Agent
email: gzileni@hotmail.com
description: >-
  A Python library for advanced memory management in AI agent applications
version: 2.0.16

github_username:  gzileni
linkedin_username: gzileni

plugins:
 - jekyll-feed
 - jekyll-seo-tag

social:
  - icon: fab fa-github
    link: https://github.com/gzileni/memory-agent
  - icon: fab fa-linkedin
    link: https://www.linkedin.com/in/gzileni