theme: minima
title: Memory Agent
description: >-
  A Python library for advanced memory management in AI agent applications
version: 1.0.43
minima:
  navigation:
      - title: "Home"
        url: /
      - title: "Versione: v1.0.43"
        url: "#"
      - title: "GitHub"
        url: https://github.com/gzileni/memory_agent
  social_links:
    - { platform: github,         user_url: "https://github.com/gzileni/memory-agent" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/gzileni" }